### PR TITLE
Make rebus instances signletons (by default)

### PR DESCRIPTION
**Pull request by yosefd**
CC @eladb

### CODE REVIEW

**Comment by eladb** [comment]
Looks good.

I would consider changing the surface semantics from `singletons` to `shared` or something like that. Also, update your `README` file.

**Comment by yosefd** [comment]
I will update readme after rebus will become operational in our code, though I am quite confident with it already.
Anyway, need 1st to solve the problem with travis that fails to install. Do you have a clue why this happens?

**Comment by eladb** [comment]
Can you please re-send this email?

On 3/1/12 2:05 PM, "Yosef Dinerstein"
<reply+i-3433147-fe9bcc8c7cda0aefe26169d7b6c59dd90cd52cca-598796@reply.gith
ub.com> wrote:

**Comment by yosefd** [comment]
I've resent.

Why not good to call those singletons? This is exactly what they are. For every folder, rebus returns singleton assigned to the folder.

**Comment by eladb** [comment]
True, but I'm not sure it's clear enough in the API level.
Elad.

On 3/1/12 3:17 PM, "Yosef Dinerstein"
<reply+i-3433147-fe9bcc8c7cda0aefe26169d7b6c59dd90cd52cca-598796@reply.gith
ub.com> wrote:

**Pull request merged**
